import dotenv from 'dotenv';

dotenv.config(); 

const ACCESS_SECRET_KEY = process.env.ACCESS_SECRET_KEY;
const REFRESH_SECRET_KEY = process.env.REFRESH_SECRET_KEY;
const SECRET_KEY = process.env.SECRET_KEY;

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_CALLBACK_URL = process.env.GOOGLE_CALLBACK_URL;

const CLIENT_REDIRECT_URL = process.env.CLIENT_REDIRECT_URL;
const CLIENT_ERROR_URL = process.env.CLIENT_ERROR_URL;

export { 
    ACCESS_SECRET_KEY, 
    REFRESH_SECRET_KEY,
    SECRET_KEY, 
    GOOGLE_CLIENT_ID, 
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL,
    CLIENT_REDIRECT_URL,
    CLIENT_ERROR_URL
};